#!name=上汽大众
#!desc=上汽大众-签到
#脚本功能:上汽大众-签到
#更新时间:2025-07-15
#源文件地址: https://raw.githubusercontent.com/wf021325/qx/master/task/csvw.js
#使用声明：️仅供学习交流，🈲️商业用途
[URL Rewrite]
# 这是屏蔽旧版APP弹出更新的，开启重写可以使用旧版
^https?:\/\/api\.mos\.csvw\.com\/mos\/app-update\/api\/v1\/app\/update$ - reject-dict

[Script]
csvw = type=http-request, pattern=^https?:\/\/api\.mos\.csvw\.com\/mos\/security\/api\/v1\/app\/at\/actions\/refresh$, script-path=https://github.com/braless/module/raw/main/js/csvw.js, timeout=60

上汽大众 = type=cron, cronexp=1 0 * * *, script-path=https://github.com/braless/module/raw/main/js/csvw.js, timeout=120, wake-system=1

[MITM]
hostname = %APPEND% api.mos.csvw.com


